# Generated by Django 3.2 on 2022-08-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_mentor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
